-- Migration: 20260120_user_browsers.sql
-- Description: Create user_browsers table for Chrome Extension integration
-- This table stores registered browser extensions linked to user accounts

-- Create the user_browsers table
CREATE TABLE public.user_browsers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    extension_id TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL DEFAULT 'My Browser',
    browser_info JSONB DEFAULT '{}',
    token_hash TEXT NOT NULL,
    is_online BOOLEAN DEFAULT FALSE,
    last_seen_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add helpful comments
COMMENT ON TABLE public.user_browsers IS 'Registered Chrome extension instances linked to user accounts';
COMMENT ON COLUMN public.user_browsers.extension_id IS 'Unique identifier generated by the Chrome extension';
COMMENT ON COLUMN public.user_browsers.token_hash IS 'SHA-256 hash of issued browser token for validation';
COMMENT ON COLUMN public.user_browsers.browser_info IS 'Metadata: {browser, version, os, last_ip}';
COMMENT ON COLUMN public.user_browsers.is_online IS 'Whether WebSocket is currently connected';

-- Create indexes for common query patterns
CREATE INDEX idx_user_browsers_user_id ON public.user_browsers(user_id);
CREATE INDEX idx_user_browsers_extension_id ON public.user_browsers(extension_id);
CREATE INDEX idx_user_browsers_is_online ON public.user_browsers(is_online);

-- Enable Row Level Security
ALTER TABLE public.user_browsers ENABLE ROW LEVEL SECURITY;

-- RLS Policies: Users can only access their own browsers
CREATE POLICY "Users can view own browsers"
    ON public.user_browsers FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own browsers"
    ON public.user_browsers FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own browsers"
    ON public.user_browsers FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own browsers"
    ON public.user_browsers FOR DELETE
    USING (auth.uid() = user_id);

-- Service role bypass for backend operations (update is_online, etc.)
CREATE POLICY "Service role has full access"
    ON public.user_browsers FOR ALL
    USING (auth.role() = 'service_role');

-- Trigger for updated_at timestamp
CREATE OR REPLACE FUNCTION public.update_user_browsers_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_user_browsers_updated_at
    BEFORE UPDATE ON public.user_browsers
    FOR EACH ROW
    EXECUTE FUNCTION public.update_user_browsers_updated_at();

-- Grant permissions
GRANT ALL ON public.user_browsers TO authenticated;
GRANT ALL ON public.user_browsers TO service_role;
